steps:
  - command: |
      cd .. && git clone git@github.com:EOSIO/eosio-java.git && cd eosio-java && git checkout develop && cd .. && cd eosio-java-softkey-signature-provider
    label: "Fetch Eosio-Java Lib"
    agents:
     - "queue=automation-android-builder-fleet"

  - wait

  - command: |
      gradle build
    label: "Build Library"
    agents:
     - "queue=automation-android-builder-fleet"
     

  - command: |
      gradle test
    label: "Run Tests"
    agents:
     - "queue=automation-android-builder-fleet"

  - wait

  - command: "echo 'Success!!'"
    label: ":trophy: Success"
    agents:
     - "queue=automation-android-builder-fleet"